import subprocess
import time
import os

def vycistit():
    if os.name == "nt":
        os.system("cls")
    else:
        os.system("clear")

print("#####################################")
print("#...................................#")
print("#.......Welcome in DDOS attack......#")
print("#.......Created by: Danb1551........#")
print("#.........Web: TERMUX.WZ.CZ.........#")
print("#.....Instagram: hackit.121212......#")
print("#..E-mail: hackit.121212@gmail.com..#")
print("#...ONLY FOR EDUCATIONAL PURPOSES...#")
print("#...................................#")
print("#####################################")
time.sleep(0.25)
print()
print("Select:")
print("{1.} DDOS Attack")
print("{2.} Password generator")
print("{3.} Instagram bruteforce attack")
volba = int(input())
if volba == 1:
    print("STARTING ATTACK...../")
    time.sleep(0.25)
    vycistit()
    print("STARTING ATTACK.....-")
    time.sleep(0.25)
    vycistit()
    print("STARTING ATTACK.....")
    time.sleep(0.25)
    vycistit()
    print("STARTING ATTACK.....|")
    time.sleep(0.25)
    vycistit()
    print("STARTING ATTACK...../")
    time.sleep(0.25)
    vycistit()
    print("STARTING ATTACK.....-")
    time.sleep(0.25)
    vycistit()
    print("STARTING ATTACK.....|")
    time.sleep(0.25)
    vycistit()
    print("STARTING ATTACK...../")
    time.sleep(0.25)
    vycistit()
    print("STARTING ATTACK.....-")
    time.sleep(0.25)
    vycistit()
    print("STARTING ATTACK.....|")
    time.sleep(0.25)
    vycistit()
    print("STARTING ATTACK...../")
    vycistit()
    subprocess.call(["python","attack.py"])
if volba == 2:
    print("Password generator is starting")
    time.sleep(1)
    vycistit()
    subprocess.call(["python","passgen.py"])
if volba == 3:
    print("Instagram bruteforce attack is starting............/")
    time.sleep(0.25)
    vycistit()
    print("Instagram bruteforce attack is starting............-")
    time.sleep(0.25)
    vycistit()
    print("Instagram bruteforce attack is starting............|")
    time.sleep(0.25)
    vycistit()
    print("Instagram bruteforce attack is starting............/")
    time.sleep(0.25)
    vycistit()
    print("Instagram bruteforce attack is starting............/")
    time.sleep(0.25)
    vycistit()
    print("Instagram bruteforce attack is starting............-")
    time.sleep(0.25)
    vycistit()
    print("Instagram bruteforce attack is starting............|")
    time.sleep(0.25)
    vycistit()
    print("Instagram bruteforce attack is starting............/")
    time.sleep(0.25)
    vycistit()
    print("Instagram bruteforce attack is starting............/")
    time.sleep(0.25)
    vycistit()
    print("Instagram bruteforce attack is starting............-")
    time.sleep(0.25)
    vycistit()
    print("Instagram bruteforce attack is starting............|")
    time.sleep(0.25)
    vycistit()
    print("Instagram bruteforce attack is starting............/")
    time.sleep(0.25)
    vycistit()
    subprocess.call(["python","instahack.py"])